# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bronko/projects/tetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bronko/projects/tetris

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bronko/projects/tetris/CMakeFiles /home/bronko/projects/tetris//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bronko/projects/tetris/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tetris

# Build rule for target.
tetris: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tetris
.PHONY : tetris

# fast build rule for target.
tetris/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/build
.PHONY : tetris/fast

src/components/game.o: src/components/game.c.o
.PHONY : src/components/game.o

# target to build an object file
src/components/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/game.c.o
.PHONY : src/components/game.c.o

src/components/game.i: src/components/game.c.i
.PHONY : src/components/game.i

# target to preprocess a source file
src/components/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/game.c.i
.PHONY : src/components/game.c.i

src/components/game.s: src/components/game.c.s
.PHONY : src/components/game.s

# target to generate assembly for a file
src/components/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/game.c.s
.PHONY : src/components/game.c.s

src/components/menu.o: src/components/menu.c.o
.PHONY : src/components/menu.o

# target to build an object file
src/components/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/menu.c.o
.PHONY : src/components/menu.c.o

src/components/menu.i: src/components/menu.c.i
.PHONY : src/components/menu.i

# target to preprocess a source file
src/components/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/menu.c.i
.PHONY : src/components/menu.c.i

src/components/menu.s: src/components/menu.c.s
.PHONY : src/components/menu.s

# target to generate assembly for a file
src/components/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/components/menu.c.s
.PHONY : src/components/menu.c.s

src/draw/draw-game.o: src/draw/draw-game.c.o
.PHONY : src/draw/draw-game.o

# target to build an object file
src/draw/draw-game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-game.c.o
.PHONY : src/draw/draw-game.c.o

src/draw/draw-game.i: src/draw/draw-game.c.i
.PHONY : src/draw/draw-game.i

# target to preprocess a source file
src/draw/draw-game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-game.c.i
.PHONY : src/draw/draw-game.c.i

src/draw/draw-game.s: src/draw/draw-game.c.s
.PHONY : src/draw/draw-game.s

# target to generate assembly for a file
src/draw/draw-game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-game.c.s
.PHONY : src/draw/draw-game.c.s

src/draw/draw-menu.o: src/draw/draw-menu.c.o
.PHONY : src/draw/draw-menu.o

# target to build an object file
src/draw/draw-menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-menu.c.o
.PHONY : src/draw/draw-menu.c.o

src/draw/draw-menu.i: src/draw/draw-menu.c.i
.PHONY : src/draw/draw-menu.i

# target to preprocess a source file
src/draw/draw-menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-menu.c.i
.PHONY : src/draw/draw-menu.c.i

src/draw/draw-menu.s: src/draw/draw-menu.c.s
.PHONY : src/draw/draw-menu.s

# target to generate assembly for a file
src/draw/draw-menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/draw/draw-menu.c.s
.PHONY : src/draw/draw-menu.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/main.c.s
.PHONY : src/main.c.s

src/tools/draw-tools.o: src/tools/draw-tools.c.o
.PHONY : src/tools/draw-tools.o

# target to build an object file
src/tools/draw-tools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/draw-tools.c.o
.PHONY : src/tools/draw-tools.c.o

src/tools/draw-tools.i: src/tools/draw-tools.c.i
.PHONY : src/tools/draw-tools.i

# target to preprocess a source file
src/tools/draw-tools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/draw-tools.c.i
.PHONY : src/tools/draw-tools.c.i

src/tools/draw-tools.s: src/tools/draw-tools.c.s
.PHONY : src/tools/draw-tools.s

# target to generate assembly for a file
src/tools/draw-tools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/draw-tools.c.s
.PHONY : src/tools/draw-tools.c.s

src/tools/game-tools.o: src/tools/game-tools.c.o
.PHONY : src/tools/game-tools.o

# target to build an object file
src/tools/game-tools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/game-tools.c.o
.PHONY : src/tools/game-tools.c.o

src/tools/game-tools.i: src/tools/game-tools.c.i
.PHONY : src/tools/game-tools.i

# target to preprocess a source file
src/tools/game-tools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/game-tools.c.i
.PHONY : src/tools/game-tools.c.i

src/tools/game-tools.s: src/tools/game-tools.c.s
.PHONY : src/tools/game-tools.s

# target to generate assembly for a file
src/tools/game-tools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/game-tools.c.s
.PHONY : src/tools/game-tools.c.s

src/tools/menu-tools.o: src/tools/menu-tools.c.o
.PHONY : src/tools/menu-tools.o

# target to build an object file
src/tools/menu-tools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/menu-tools.c.o
.PHONY : src/tools/menu-tools.c.o

src/tools/menu-tools.i: src/tools/menu-tools.c.i
.PHONY : src/tools/menu-tools.i

# target to preprocess a source file
src/tools/menu-tools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/menu-tools.c.i
.PHONY : src/tools/menu-tools.c.i

src/tools/menu-tools.s: src/tools/menu-tools.c.s
.PHONY : src/tools/menu-tools.s

# target to generate assembly for a file
src/tools/menu-tools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tetris.dir/build.make CMakeFiles/tetris.dir/src/tools/menu-tools.c.s
.PHONY : src/tools/menu-tools.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tetris"
	@echo "... src/components/game.o"
	@echo "... src/components/game.i"
	@echo "... src/components/game.s"
	@echo "... src/components/menu.o"
	@echo "... src/components/menu.i"
	@echo "... src/components/menu.s"
	@echo "... src/draw/draw-game.o"
	@echo "... src/draw/draw-game.i"
	@echo "... src/draw/draw-game.s"
	@echo "... src/draw/draw-menu.o"
	@echo "... src/draw/draw-menu.i"
	@echo "... src/draw/draw-menu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tools/draw-tools.o"
	@echo "... src/tools/draw-tools.i"
	@echo "... src/tools/draw-tools.s"
	@echo "... src/tools/game-tools.o"
	@echo "... src/tools/game-tools.i"
	@echo "... src/tools/game-tools.s"
	@echo "... src/tools/menu-tools.o"
	@echo "... src/tools/menu-tools.i"
	@echo "... src/tools/menu-tools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

